version: '3.8'

services:
  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT_DB}:5432"
    volumes:
     - ./initdb:/docker-entrypoint-initdb.d
    restart: always

  order-service:
    build: ./order
    container_name: order-service
    environment:
      HOST_PORT_ORDER: ${HOST_PORT_ORDER} 
      DB_HOST: db  
      DB_PORT: 5432  
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT_ORDER}:8081"
    depends_on:
      - db
    restart: always

  payment-service:
    build: ./payment
    container_name: payment-service
    environment:
      HOST_PORT_PAYMENT: ${HOST_PORT_PAYMENT} 
      DB_HOST: db  
      DB_PORT: 5432  
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT_PAYMENT}:8082"
    depends_on:
      - db
    restart: always

  stock-service:
    build: ./stock
    container_name: stock-service
    environment:
      HOST_PORT_STOCK: ${HOST_PORT_STOCK} 
      DB_HOST: db  
      DB_PORT: 5432  
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT_STOCK}:8083"
    depends_on:
      - db
    restart: always

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator_service
    environment:
      HOST_PORT_ORCHESTRATOR: ${HOST_PORT_ORCHESTRATOR} 
      ORDER_SERVICE_HOST: order-service
      ORDER_SERVICE_PORT: 8081
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8082
      STOCK_SERVICE_HOST: stock-service
      STOCK_SERVICE_PORT: 8083
    ports:
      - "${HOST_PORT_ORCHESTRATOR}:8080"
    depends_on:
      - order-service
      - payment-service
      - stock-service
    restart: always