version: '3.8'

services:
  db:
    image: postgres:16_alpine
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${HOST_PORT_DB}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data